services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agrigest_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - agrigest

  mysql:
    image: mysql:8.0
    container_name: agrigest_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: agrigest
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - agrigest

networks:
  agrigest:

volumes:
  mysql_data:
